### ISSUE TITLE
--proxy-file isn't working

### ISSUE THREAD

**Issue by digitalohm** [m8sec/CrossLinked#24]
Having some issues using crosslinked with multiple proxies. I am able to execute things fine with no proxy, and specifying a single proxy, however the `--proxy-file` switch seems to break. 

```┌──(crosslinked)─(test㉿test)-[~/tools/crosslinked/bin]
└─$ crosslinked --proxy-file 'proxies.txt' -f '{f}{last}@microsoft.com' -j 3 -t 10 "Microsoft"

     _____                    _             _            _ 
    /  __ \                  | |   (x)     | |          | |
    | /  \/_ __ ___  ___ ___ | |    _ _ __ | | _____  __| |
    | |   | '__/ _ \/ __/ __|| |   | | '_ \| |/ / _ \/ _` |
    | \__/\ | | (_) \__ \__ \| |___| | | | |   <  __/ (_| | @m8sec
     \____/_|  \___/|___/___/\_____/_|_| |_|_|\_\___|\__,_| v0.2.0

    
Traceback (most recent call last):
  File "/home/test/tools/crosslinked/bin/crosslinked", line 8, in <module>
    sys.exit(main())
  File "/home/test/tools/crosslinked/lib/python3.10/site-packages/crosslinked/__init__.py", line 102, in main
    args = cli()
  File "/home/test/tools/crosslinked/lib/python3.10/site-packages/crosslinked/__init__.py", line 48, in cli
    return args.parse_args()
  File "/usr/lib/python3.10/argparse.py", line 1838, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 1871, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 2084, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.10/argparse.py", line 2024, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.10/argparse.py", line 1932, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.10/argparse.py", line 2467, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.10/argparse.py", line 2500, in _get_value
    result = type_func(arg_string)
  File "/home/test/tools/crosslinked/lib/python3.10/site-packages/crosslinked/__init__.py", line 47, in <lambda>
    pr.add_argument('--proxy-file', dest='proxy', default=False, type=lambda x: utils.file_exists(x), help='Load proxies from file for rotation')
  File "/home/test/tools/crosslinked/lib/python3.10/site-packages/crosslinked/utils.py", line 20, in file_exists
    return [line.strip() for line in open('filename')] if contents else filename
FileNotFoundError: [Errno 2] No such file or directory: 'filename'
```

content of proxies.txt 

```
┌──(crosslinked)─(test㉿test)-[~/tools/crosslinked/bin]
└─$ cat proxies.txt                                                                                           
workingproxy1:8888
workingproxy2:8888
workingproxy3:8888
```

**Comment by m8sec** [comment]
Hi @digitalohm, what type of proxies are you adding (http, socks4, socks5)?

**Comment by m8sec** [comment]
I also want to note, socks proxies require a `socks4://` or `socks5://` prefix - detailed in the [readme](https://github.com/m8sec/CrossLinked#proxy-rotation).

**Comment by m8sec** [comment]
Closing inactive
